server.port=8090
numerator.api.base-url=http://localhost:3000
numerator.api.path.generate-id=/numerator/test-and-set

resilience4j.instance.name=NumeratorApiClient
resilience4j.circuitbreaker.instances.NumeratorApiClient.failureRateThreshold=50
resilience4j.circuitbreaker.instances.NumeratorApiClient.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.NumeratorApiClient.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.NumeratorApiClient.slidingWindowSize=10

resilience4j.retry.instances.${resilience4j.instance.name}.maxAttempts=4
resilience4j.retry.instances.${resilience4j.instance.name}.waitDuration=1000ms
resilience4j.retry.instances.${resilience4j.instance.name}.retryExceptions=org.example.Exceptions.ExceptionService

